name: Increment version tag
on:
  schedule:
    - cron: 0 0 * * 6
jobs:
  patch:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[update:patch]')"
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
