name: Increment version tag
on:
  schedule:
    - cron: 0 0 * * 6
  workflow_dispatch:
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: head-commit
        run: echo "message=$(git show --no-patch --format=%B)" >> "$GITHUB_OUTPUT"
      - name: Bump version and push tag
        if: contains(steps.head-commit.outputs.message, '[update:patch]')
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
